public class ServerPacketProt {

   public static final ServerPacketProt field2160 = new ServerPacketProt(0, -2);
   public static final ServerPacketProt logoutFullMessage = new ServerPacketProt(1, 0);
   public static final ServerPacketProt field2117 = new ServerPacketProt(2, 0);
   public static final ServerPacketProt messageGameMessage = new ServerPacketProt(3, -1);
   public static final ServerPacketProt varpLargeMessage = new ServerPacketProt(4, 6);
   public static final ServerPacketProt field2165 = new ServerPacketProt(5, 4);
   public static final ServerPacketProt locAddChangeMessage = new ServerPacketProt(6, 4);
   public static final ServerPacketProt field2122 = new ServerPacketProt(7, 4);
   public static final ServerPacketProt mapAnimMessage = new ServerPacketProt(8, 6);
   public static final ServerPacketProt ifCloseSub = new ServerPacketProt(9, 4);
   public static final ServerPacketProt field2141 = new ServerPacketProt(10, -2);
   public static final ServerPacketProt mapProjAnimMessage = new ServerPacketProt(11, 15);
   public static final ServerPacketProt soundAreaMessage = new ServerPacketProt(12, 5);
   public static final ServerPacketProt locDelMessage = new ServerPacketProt(13, 2);
   public static final ServerPacketProt objDelMessage = new ServerPacketProt(14, 3);
   public static final ServerPacketProt objCountMessage = new ServerPacketProt(15, 7);
   public static final ServerPacketProt field2131 = new ServerPacketProt(16, 1);
   public static final ServerPacketProt updateZonePartialEnclosedMessage = new ServerPacketProt(17, -2);
   public static final ServerPacketProt field2133 = new ServerPacketProt(18, -2);
   public static final ServerPacketProt ifSetTextMessage = new ServerPacketProt(19, -2);
   public static final ServerPacketProt ifSetObjectMessage = new ServerPacketProt(20, 10);
   public static final ServerPacketProt ifSetHideMessage = new ServerPacketProt(21, 5);
   public static final ServerPacketProt updateStatMessage = new ServerPacketProt(22, 6);
   public static final ServerPacketProt midiSongMessage = new ServerPacketProt(23, 2);
   public static final ServerPacketProt field2139 = new ServerPacketProt(24, 6);
   public static final ServerPacketProt field2140 = new ServerPacketProt(25, 2);
   public static final ServerPacketProt field2137 = new ServerPacketProt(26, 5);
   public static final ServerPacketProt field2135 = new ServerPacketProt(27, -2);
   public static final ServerPacketProt field2143 = new ServerPacketProt(28, 0);
   public static final ServerPacketProt field2144 = new ServerPacketProt(29, 0);
   public static final ServerPacketProt ifSetPlayerHeadMessage = new ServerPacketProt(30, 4);
   public static final ServerPacketProt field2175 = new ServerPacketProt(31, 6);
   public static final ServerPacketProt field2147 = new ServerPacketProt(32, -2);
   public static final ServerPacketProt field2148 = new ServerPacketProt(33, -2);
   public static final ServerPacketProt field2149 = new ServerPacketProt(34, 1);
   public static final ServerPacketProt ifSetNpcHeadMessage = new ServerPacketProt(35, 6);
   public static final ServerPacketProt field2151 = new ServerPacketProt(36, 6);
   public static final ServerPacketProt setNewCookieTokenSomething = new ServerPacketProt(37, -1);
   public static final ServerPacketProt field2180 = new ServerPacketProt(38, -2);
   public static final ServerPacketProt field2154 = new ServerPacketProt(39, 4);
   public static final ServerPacketProt field2155 = new ServerPacketProt(40, 5);
   public static final ServerPacketProt field2156 = new ServerPacketProt(41, 8);
   public static final ServerPacketProt field2157 = new ServerPacketProt(42, 14);
   public static final ServerPacketProt field2162 = new ServerPacketProt(43, -2);
   public static final ServerPacketProt updateInvPartialMessage = new ServerPacketProt(44, -2);
   public static final ServerPacketProt updatePrivateMessage = new ServerPacketProt(45, -1);
   public static final ServerPacketProt field2161 = new ServerPacketProt(46, 2);
   public static final ServerPacketProt worldHopAction = new ServerPacketProt(47, -1);
   public static final ServerPacketProt ifSetClanMessage = new ServerPacketProt(48, 12);
   public static final ServerPacketProt field2164 = new ServerPacketProt(49, 4);
   public static final ServerPacketProt field2123 = new ServerPacketProt(50, 10);
   public static final ServerPacketProt rebuildRegionMessage = new ServerPacketProt(51, -2);
   public static final ServerPacketProt triggerOnDialogAbortMessage = new ServerPacketProt(52, 0);
   public static final ServerPacketProt field2153 = new ServerPacketProt(53, -2);
   public static final ServerPacketProt field2142 = new ServerPacketProt(54, -1);
   public static final ServerPacketProt field2170 = new ServerPacketProt(55, 20);
   public static final ServerPacketProt field2171 = new ServerPacketProt(56, -2);
   public static final ServerPacketProt field2172 = new ServerPacketProt(57, 28);
   public static final ServerPacketProt field2132 = new ServerPacketProt(58, -2);
   public static final ServerPacketProt updateIgnoresMessage = new ServerPacketProt(59, 8);
   public static final ServerPacketProt updateRunEnergyMessage = new ServerPacketProt(60, 1);
   public static final ServerPacketProt updateFriendsMessage = new ServerPacketProt(61, 6);
   public static final ServerPacketProt runClientScriptMessage = new ServerPacketProt(62, -2);
   public static final ServerPacketProt varpSmallMessage = new ServerPacketProt(63, 3);
   public static final ServerPacketProt updateZonePartialFollowsMessage = new ServerPacketProt(64, 2);
   public static final ServerPacketProt synthSoundMessage = new ServerPacketProt(65, 5);
   public static final ServerPacketProt setOpPlayerMessage = new ServerPacketProt(66, -1);
   public static final ServerPacketProt setMapFlagMessage = new ServerPacketProt(67, 2);
   public static final ServerPacketProt field2183 = new ServerPacketProt(68, 1);
   public static final ServerPacketProt field2184 = new ServerPacketProt(69, 8);
   public static final ServerPacketProt updateInvFullMessage = new ServerPacketProt(70, -2);
   public static final ServerPacketProt updateRunWeightMessage = new ServerPacketProt(71, 2);
   public static final ServerPacketProt updateRebootTimerMessage = new ServerPacketProt(72, 2);
   public static final ServerPacketProt field2188 = new ServerPacketProt(73, 0);
   public static final ServerPacketProt field2115 = new ServerPacketProt(74, 1);
   public static final ServerPacketProt field2121 = new ServerPacketProt(75, 6);
   public static final ServerPacketProt MAYBE_HINT_ICON = new ServerPacketProt(76, 6);
   public static final ServerPacketProt ifOpenSubMessage = new ServerPacketProt(77, 7);
   public static final ServerPacketProt updateClanFriendsMaybe = new ServerPacketProt(78, 0);
   public static final ServerPacketProt field2194 = new ServerPacketProt(79, -2);
   public static final ServerPacketProt field2195 = new ServerPacketProt(80, 2);
   public static final ServerPacketProt field2196 = new ServerPacketProt(81, -2);
   public static final ServerPacketProt ifMoveSubMessage = new ServerPacketProt(82, 8);
   public static final ServerPacketProt field2198 = new ServerPacketProt(83, 6);
   public static final ServerPacketProt ifOpenTopMessage = new ServerPacketProt(84, 2);
   public static final ServerPacketProt field2200 = new ServerPacketProt(85, 1);
   public final int field2201;
   public final int length;

   ServerPacketProt(int i_1, int i_2) {
      this.field2201 = i_1;
      this.length = i_2;
   }

}
